version: '3.8'

services:
  backend:
    image: agapeejeh/backend:v1
    build: ./backend
    ports: 
      - "5000:5000"
    networks:
      - app-networks   

  frontend:
    image: agapeejeh/frontend:v1
    build: ./frontend
    ports: 
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - app-networks   

networks:
  app-networks: